aws.region: ${AWS_REGION:us-east-2}
aws.accessKey: ${AWS_ACCESS_KEY_ID}
aws.secretKey: ${AWS_SECRET_ACCESS_KEY}
aws.sessionToken: ${AWS_SESSION_TOKEN}
sample.sqs.queue: leo-sqs-usea2-AWSLeoDev-Mobias-Syndicator-queue-test-kevin
