#Prevent batch jobs from starting automatically
cloud.aws.credentials.accessKey: ilaugsjdlkahgsdlaksdhg
cloud.aws.credentials.secretKey: aöksjdhöadjs,höalsdhjköalsdjhasd+
rdsPassword: someVerySecretPassword

## you can get into iam page [https://console.aws.amazon.com/iam/home]
#cloud.aws.credentials.accessKey={accessKey}
#cloud.aws.credentials.secretKey={secretKey}
#
## example : ap-northeast-1
#cloud.aws.region={region}
#
## example : s3-bucket-test-1
#cloud.aws.s3.bucket={bucket}