aws.region: {region}
aws.accessKey: {accessKey}
aws.secretKey: {secretKey}
aws.sqs.payload-types-map:
    samplequeue_protobuf_complicated_message: org.tnmk.practicespringaws.pro05.SampleComplicatedMessageProto
    samplequeue_protobuf_simple_message: org.tnmk.practicespringaws.pro05.SampleMessageProto

sample.sqs.queue: samplequeue_protobuf_complicated_message


